# Generated by Django 4.1.1 on 2022-10-02 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shortner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1000, verbose_name='Website URL')),
                ('slug', models.CharField(max_length=15, unique=True, verbose_name='Short Link')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('is_active', models.BooleanField()),
            ],
        ),
    ]
